# ==========================================
# Базовые параметры настройки конфигурации проекта
# ==========================================

# Имя базы данных PostgreSQL. Обычно оставляют "postgres".
dbname: postgres       # В классе менять не надо

# Пользователь PostgreSQL. Замените на свой логин от БД.
user: postgres         # Замените на свой логин от БД в классе

# Пароль пользователя PostgreSQL. Замените на свой пароль.
password: qwerty       # Замените на свой пароль от БД в классе

# Сервер базы данных. Обычно оставляют localhost,
# но в классе могли использовать IP, например 192.168.0.48
host: localhost        # Замените на адрес своего сервера БД в классе

# Схема таблиц в базе данных. Обычно public.
dbtableprefix: "public."  # Замените на свою схему при необходимости

